import json
import os

from anthropic import AsyncAnthropic
from dotenv import load_dotenv

from app.models import JudgeResult

load_dotenv()

client = AsyncAnthropic(api_key=os.getenv("ANTHROPIC_API_KEY"))

CLAUDE_MODEL = os.getenv("CLAUDE_MODEL", "claude-sonnet-4-5-20250929")

SYSTEM_PROMPT = """\
You are an expert content analyst specializing in digital media evaluation. \
Analyze the provided content and produce structured assessments across three dimensions.

## 1. AI-Generated Content Assessment

Evaluate whether the content appears AI-generated or human-created.

For TEXT, consider:
- Repetitive sentence structures or unusual uniformity in paragraph length
- Lack of personal anecdotes, idiosyncratic phrasing, or strong subjective opinions
- Overly formal or "smoothed out" language
- Absence of typos or natural colloquialisms
- Hedging patterns common in LLM outputs ("It's important to note that...")
- Formulaic structure (intro → body → conclusion with neat transitions)

For IMAGES / VIDEO FRAMES, evaluate:
- Composition, subjects, context, and style of what is depicted
- Contextual clues and metadata hints
- NOTE: You cannot definitively determine whether an image was generated by AI \
from visual inspection alone. Base your assessment on content characteristics, \
not on claiming visual detection.

IMPORTANT: Express appropriate uncertainty. A probability near 0.5 with label \
"uncertain" is valid when signals are mixed.

## 2. Virality Potential (score 0–100)

Consider: emotional resonance, shareability, timeliness, novelty, simplicity, \
visual appeal, controversy/debate potential, and relatability.

## 3. Distribution Analysis

Identify specific audiences, communities, and platforms where this content would \
resonate. For each, explain WHY it would appeal to them.

Be specific in your reasoning — avoid vague or generic explanations. \
Ground assessments in observable features of the content."""

# JSON schema for Claude structured output (matches JudgeResult)
JUDGE_RESULT_SCHEMA = {
    "type": "object",
    "properties": {
        "content_type": {
            "type": "string",
            "enum": ["text", "image", "video"],
        },
        "ai_generated": {
            "type": "object",
            "properties": {
                "probability": {"type": "number"},
                "label": {
                    "type": "string",
                    "enum": [
                        "ai_generated",
                        "human_generated",
                        "uncertain",
                    ],
                },
                "reasoning": {"type": "string"},
            },
            "required": ["probability", "label", "reasoning"],
            "additionalProperties": False,
        },
        "virality": {
            "type": "object",
            "properties": {
                "score": {"type": "integer"},
                "reasoning": {"type": "string"},
            },
            "required": ["score", "reasoning"],
            "additionalProperties": False,
        },
        "distribution": {
            "type": "object",
            "properties": {
                "segments": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "audience": {"type": "string"},
                            "resonance_reason": {"type": "string"},
                        },
                        "required": ["audience", "resonance_reason"],
                        "additionalProperties": False,
                    },
                }
            },
            "required": ["segments"],
            "additionalProperties": False,
        },
        "summary": {"type": "string"},
    },
    "required": [
        "content_type",
        "ai_generated",
        "virality",
        "distribution",
        "summary",
    ],
    "additionalProperties": False,
}


async def _call_claude(content: list[dict]) -> JudgeResult:
    """Send content blocks to Claude and return a parsed JudgeResult."""
    response = await client.messages.create(
        model=CLAUDE_MODEL,
        max_tokens=4096,
        system=SYSTEM_PROMPT,
        messages=[{"role": "user", "content": content}],
        output_config={
            "format": {
                "type": "json_schema",
                "schema": JUDGE_RESULT_SCHEMA,
            }
        },
    )

    if response.stop_reason == "refusal":
        raise ValueError(
            "Claude refused to analyze this content due to safety policies."
        )
    if response.stop_reason == "max_tokens":
        raise ValueError(
            "Analysis was truncated — the content may be too complex "
            "for a single analysis pass."
        )

    raw = response.content[0].text
    return JudgeResult(**json.loads(raw))


async def analyze_text(text: str) -> JudgeResult:
    """Analyze text content."""
    content = [
        {
            "type": "text",
            "text": f"Analyze the following text content:\n\n{text}",
        }
    ]
    return await _call_claude(content)


async def analyze_with_images(
    images: list[dict],
    text_context: str = "",
    content_type: str = "image",
) -> JudgeResult:
    """Analyze image or video content (frames) with optional text context.

    Each image dict must have "data" (base64) and "media_type" keys.
    """
    # Claude works best with images before text
    content: list[dict] = []
    for i, img in enumerate(images):
        label = f"Frame {i + 1}:" if content_type == "video" else f"Image {i + 1}:"
        content.append({"type": "text", "text": label})
        content.append(
            {
                "type": "image",
                "source": {
                    "type": "base64",
                    "media_type": img["media_type"],
                    "data": img["data"],
                },
            }
        )

    if text_context:
        content.append(
            {"type": "text", "text": f"\nAdditional context:\n{text_context}"}
        )

    content.append(
        {
            "type": "text",
            "text": f"Analyze this {content_type} content according to your instructions.",
        }
    )

    return await _call_claude(content)
