from __future__ import annotations

import json
import time

from anthropic import APIStatusError, AsyncAnthropic
from tenacity import (
    retry,
    retry_if_exception,
    stop_after_attempt,
    wait_exponential,
)

from app.config import get_settings
from app.logging_config import get_logger
from app.models import JudgeResult

log = get_logger(__name__)

# --------------------------------------------------------------------------
# Client — lazy singleton
# --------------------------------------------------------------------------

_client: AsyncAnthropic | None = None


def _get_client() -> AsyncAnthropic:
    """Return (and cache) an AsyncAnthropic client."""
    global _client
    if _client is None:
        settings = get_settings()
        _client = AsyncAnthropic(api_key=settings.anthropic_api_key)
    return _client


# --------------------------------------------------------------------------
# Prompt & schema
# --------------------------------------------------------------------------

SYSTEM_PROMPT = """\
You are an expert content analyst specializing in digital media evaluation. \
Analyze the provided content and produce structured assessments across three dimensions.

## 1. AI-Generated Content Assessment

Evaluate whether the content appears AI-generated or human-created.

For TEXT, consider:
- Repetitive sentence structures or unusual uniformity in paragraph length
- Lack of personal anecdotes, idiosyncratic phrasing, or strong subjective opinions
- Overly formal or "smoothed out" language
- Absence of typos or natural colloquialisms
- Hedging patterns common in LLM outputs ("It's important to note that...")
- Formulaic structure (intro → body → conclusion with neat transitions)

For IMAGES / VIDEO FRAMES, evaluate:
- Composition, subjects, context, and style of what is depicted
- Contextual clues and metadata hints
- NOTE: You cannot definitively determine whether an image was generated by AI \
from visual inspection alone. Base your assessment on content characteristics, \
not on claiming visual detection.

IMPORTANT: Express appropriate uncertainty. A probability near 0.5 with label \
"uncertain" is valid when signals are mixed.

## 2. Virality Potential (score 0–100)

Consider: emotional resonance, shareability, timeliness, novelty, simplicity, \
visual appeal, controversy/debate potential, and relatability.

## 3. Distribution Analysis

Identify specific audiences, communities, and platforms where this content would \
resonate. For each, explain WHY it would appeal to them.

Be specific in your reasoning — avoid vague or generic explanations. \
Ground assessments in observable features of the content."""

JUDGE_RESULT_SCHEMA = {
    "type": "object",
    "properties": {
        "content_type": {
            "type": "string",
            "enum": ["text", "image", "video"],
        },
        "ai_generated": {
            "type": "object",
            "properties": {
                "probability": {"type": "number"},
                "label": {
                    "type": "string",
                    "enum": [
                        "ai_generated",
                        "human_generated",
                        "uncertain",
                    ],
                },
                "reasoning": {"type": "string"},
            },
            "required": ["probability", "label", "reasoning"],
            "additionalProperties": False,
        },
        "virality": {
            "type": "object",
            "properties": {
                "score": {"type": "integer"},
                "reasoning": {"type": "string"},
            },
            "required": ["score", "reasoning"],
            "additionalProperties": False,
        },
        "distribution": {
            "type": "object",
            "properties": {
                "segments": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "audience": {"type": "string"},
                            "resonance_reason": {"type": "string"},
                        },
                        "required": ["audience", "resonance_reason"],
                        "additionalProperties": False,
                    },
                }
            },
            "required": ["segments"],
            "additionalProperties": False,
        },
        "summary": {"type": "string"},
    },
    "required": [
        "content_type",
        "ai_generated",
        "virality",
        "distribution",
        "summary",
    ],
    "additionalProperties": False,
}


# --------------------------------------------------------------------------
# Retry predicate — only retry transient server-side errors
# --------------------------------------------------------------------------

def _is_retryable(exc: BaseException) -> bool:
    if isinstance(exc, APIStatusError) and exc.status_code in (429, 500, 502, 503, 529):
        return True
    return False


# --------------------------------------------------------------------------
# Core call
# --------------------------------------------------------------------------

@retry(
    retry=retry_if_exception(_is_retryable),
    stop=stop_after_attempt(3),
    wait=wait_exponential(multiplier=1, min=1, max=15),
    reraise=True,
)
async def _call_claude(content: list[dict]) -> JudgeResult:
    """Send content blocks to Claude and return a parsed JudgeResult."""
    settings = get_settings()
    client = _get_client()

    t0 = time.monotonic()
    response = await client.messages.create(
        model=settings.claude_model,
        max_tokens=4096,
        system=SYSTEM_PROMPT,
        messages=[{"role": "user", "content": content}],
        output_config={
            "format": {
                "type": "json_schema",
                "schema": JUDGE_RESULT_SCHEMA,
            }
        },
    )
    elapsed_ms = round((time.monotonic() - t0) * 1000)

    log.info(
        "claude_response",
        model=settings.claude_model,
        stop_reason=response.stop_reason,
        latency_ms=elapsed_ms,
        input_tokens=getattr(response.usage, "input_tokens", None),
        output_tokens=getattr(response.usage, "output_tokens", None),
    )

    if response.stop_reason == "refusal":
        raise ValueError(
            "Claude refused to analyze this content due to safety policies."
        )
    if response.stop_reason == "max_tokens":
        raise ValueError(
            "Analysis was truncated — the content may be too complex "
            "for a single analysis pass."
        )

    raw = response.content[0].text
    try:
        data = json.loads(raw)
    except json.JSONDecodeError as e:
        log.error("json_parse_failed", raw_preview=raw[:200], error=str(e))
        raise ValueError("Failed to parse Claude response as JSON.") from e

    return JudgeResult(**data)


# --------------------------------------------------------------------------
# Public API
# --------------------------------------------------------------------------

async def analyze_text(text: str) -> JudgeResult:
    """Analyze text content."""
    content = [
        {
            "type": "text",
            "text": f"Analyze the following text content:\n\n{text}",
        }
    ]
    return await _call_claude(content)


async def analyze_with_images(
    images: list[dict],
    text_context: str = "",
    content_type: str = "image",
) -> JudgeResult:
    """Analyze image or video content (frames) with optional text context.

    Each image dict must have "data" (base64) and "media_type" keys.
    """
    content: list[dict] = []
    for i, img in enumerate(images):
        label = f"Frame {i + 1}:" if content_type == "video" else f"Image {i + 1}:"
        content.append({"type": "text", "text": label})
        content.append(
            {
                "type": "image",
                "source": {
                    "type": "base64",
                    "media_type": img["media_type"],
                    "data": img["data"],
                },
            }
        )

    if text_context:
        content.append(
            {"type": "text", "text": f"\nAdditional context:\n{text_context}"}
        )

    content.append(
        {
            "type": "text",
            "text": f"Analyze this {content_type} content according to your instructions.",
        }
    )

    return await _call_claude(content)
